server:
    port: 9999
springdoc:
    swagger-ui:
        path: /swagger-ui.html
logging:
    level:
        com.pocket.gocooking.system.mapper: debug

spring:
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/go_cooking?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
    data:
        redis:
            port: 6379
            host: localhost
    cache:
        redis:
            time-to-live: 1800000
mybatis:
    type-aliases-package: com.pocket.gocooking.system.entity
    mapper-locations: classpath:mapper/sys/*.xml
