server:
  port: 9999
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    com.hexadecimal: debug

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/go_cooking?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: pzf
      password: pzf299793
      roles:
        - user
        - admin
